# 1 워크플로의 이름 지정 (CI를 실행하기 위한 스크립트의 모음이므로 CI)
name: CI

# 2 워크플로가 시작될 조건 지정
# main 브랜치에 푸시를 할때마다 워크플로를 시작하도록 작성
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정 (윈도우나 리눅스같은 실행 환경을 지정)
    # 4 실행 스텝 지정(그룹화)
    steps:
      - uses: actions/checkout@v4
        # uses 키워드는 지정한 리포지터리를 확인하고 코드에 대한 작업을 실행 가능
        # action/checkout에는 checkout이라는 작업의 v3 버전을 실행함

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

        # name : 스텝의 이름을 지정함
        # run : 실행할 명렁어를 입력.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        # ./gradlew clean build에는 그레들을 사용해 프로젝트를 빌드 이전 상태로 돌리고
        # 다시 빌드하는 명령어를 실행함